### ISSUE TITLE
Undefined behaviours on the DCPU

### ISSUE THREAD

**Issue by Yamakaky** [techcompliant/TC-Specs#22] opened 2016-09-22 01:12 UTC
- Initial RAM content
- Initial registers content except
  - PC = 0
  - SP = 0xffff
  - IA is technically undefined but values other than 0 would be dumb
- Instruction with an invalid basic or special opcode
- `HWQ` or `HWI` with an invalid device id
- More than 256 queued interrupts
- (BTW, the "Interrupts" explanation could be clearer)
- Connecting or disconnecting hardware
- Overflowing
  - multi-bytes instruction with PC = 0xffff
  - LEM palette, font or video RAM at 0xffff
  - maybe others?
- LEM default font and palette
- Invalid command selector (`A` content) when `HWI`

Proposal
- Initial RAM undefined
- All registers to 0 except `SP` to 0xffff
- Invalid opcode: undefined (better?) or NOP
- Invalid device id: undefined (better?) or NOP
- 256 int: drop new interrupts (better?) or undefined
- Connecting/disconnectiong: undefined
- PC overflow while decoding: undefined (better?) or wrap
  - should not be a limitation for most programs, indicates a bug most of the time
- memmap overflow: undefined
  - should not be a limitation for most programs, indicates a bug most of the time
- Defaults for the LEM from https://github.com/techcompliant/isiCPU/blob/master/hardware/nya.c
- Invalid command selector: undefined (better?) or NOP

**Comment by Yamakaky** [comment] 2016-09-22 01:14
Some are not a problem, like undefined RAM and registers, but some could be standardised like the overflows, IA initial value and such. Any way, it should be mentioned in the doc. Especially, a lot of program assume that all emulators initialises the RAM and the registers to 0 ([mine](https://github.com/Yamakaky/dcpu) doesn't ;)).
BTW, where could I find the latest DCPU specs?

**Comment by andyleap** [comment] 2016-09-22 03:41
My preference:
- All registers set to 0, except SP to 0xFFFF on reset (this includes IA)
- Interrupt queue cleared on reset
- Ram unchanged (i.e. retaining prior values, except for the flash rom "Write contents to ram at offset 0 on DCPU reset" type thing), except on initial "creation" or whatever, in which case the ram is set to random values.
- Overflow: 
  - PC wraps around, so your instruction could be at address 0xFFFF, with it reading additional word at 0x0000. (Note, technically, there is no multi-word instruction, just single word instructions with additional word datas.  Nitpick, but reason for them to operate that way)
  - "Memmapped" data should "fail", creatively or otherwise, if mapped to be "hanging" off the end of memory

Current handling (in my emulator at least), but no real preference:
- Invalid opcode: handled as a NOP, but no promises on that.
- `HWQ` and `HWI` on invalid: `HWQ` returns all 0's, `HWI` does nothing
- More then 256 queued interrupts: interrupt ignored
- Connecting/Disconnecting hardware: Currently illegal while DCPU is running.
- LEM default font/palette: https://github.com/techcompliant/isiCPU/blob/master/hardware/nya.c
- Interrupts explanation: Agreed, fairly complex, and not well written.  I'm currently handling it as "all interrupts are put on the queue, they may just be pulled right off before the next instruction."

As for the DCPU specs, I've pushed up a PR for getting them into this repo, you can see it directly at https://github.com/techcompliant/TC-Specs/blob/andyleap-patch-1/CPU/DCPU.md for now, but we should get it merged in soon.

**Comment by Yamakaky** [comment] 2016-09-22 04:25
I updated the first post. `(better?)` indicates what I prefer.

**Comment by andyleap** [comment] 2016-09-22 04:52
"undefined" is not very helpful... what does an undefined opcode mean? what does ram undefined mean? 

Connecting/Disconnecting hardware on a running DCPU is not allowed.

Invalid command selector for HWI is currently handled as a NOP in the emulators I've seen, and that's what I'd prefer as well

**Comment by Yamakaky** [comment] 2016-09-22 05:06
If the RAM is set to random values at init, then it's content is undefined ^^

for the opcode, undefined means that the spec doesn't define what should be done. For example, a simple emulator could ignore it while a debugger would stop the execution.

not allowed == undefined if it happens, no?

why not for the NOP for the command selector and hardware id.

Any other thoughts, from @Meisaka for example?

**Comment by azertyfun** [comment] 2016-09-22 06:54
For reference: [In the original DCPU-16 specs](https://web.archive.org/web/20130905082541/http://dcpu.com/dcpu-16/), over 256 interrupts used to set the DCPU on fire (section interrupts, first paragraph). On notch's emulator, that meant the RAM got randomly corrupted over time.

**Comment by Meisaka** [comment] 2016-09-22 07:27
Currently in the emulator being used:
- sets all registers to zero including `SP` and `IA`.
- Of special note `SP` is actually "empty" when it's zero, a value of `0xffff` would indicate one DCPU byte on the stack. Decrement happens before write.
- the interrupt queue and skipping state are reset.
- The DCPU zeros out the RAM on reset, before the ROM loads.
- Excess interrupts are dropped.
- Undefined opcodes are partially decoded (i.e. push/pop), but do nothing.
- HWI on non-existent hardware has no effect other than using cycles.
- HWQ on non-existent hardware zeros A,B,C,X,Y
- Overflow has no special behavior, memory access is all mod 65536
- Sending commands via HWI that devices don't support usually has no effect.
- while TC probably doesn't let you remove/add hardware to a running DCPU, this can be done in the emulator, values for HWN would be wrong, devices could be queried with HWQ and get different results if a device is added/removed from a "slot". most DCPU software also would not support this. A Reset would resolve this condition back to "well-defined".
- A LEM screen (for example) mapped at the end of memory will wrap around.

**Comment by Yamakaky** [comment] 2016-09-23 05:29
I can live with @Meisaka 's behaviour, except
- one nick-picking: "Sending commands via HWI that devices don't support has no effect." (without the "usually").
- do we really want to ignore ill-formed instructions? On linux, the program gets a "SIGILL(4) Illegal Instruction", with coredump by default. Executing such instruction is obviously a bug so I'm not really comfortable continuing the execution. Same thing to a lesser extent to hwi and hwq.
- we can simply say that adding/removing hardware stays undefined
- forgot about HLT: I thought it stopped completely the CPU, but it just waits for the next hardware interrupt? The spec only says "eternal interrupt".

**Comment by Yamakaky** [comment] 2016-09-30 19:49
Any [Word of God](http://tvtropes.org/pmwiki/pmwiki.php/Main/WordOfGod)? ^^

**Comment by andyleap** [comment] 2016-09-30 20:47
I'm not sure I'm willing to say "has no effect", though I suppose it could just be "it does support it, it just doesn't do what you might expect" or something.

The seemingly obvious way to handle ill-formed instructions would be to throw an interrupt, but that has the issue of sending interrupts when the software may not be ready to handle them.  One thought on that would be to have CPU generated interrupts use the number 0, as that is (in all cases that I'm aware) a value for "Disable interrupts" for hardware, so no hardware should be capable of generating it, though that still has the issue of being an "unexpected" interrupt

Adding/Removing hardware while the DCPU:  Do you open your computer and disconnect your GPU and plug another one in while it's turned on?  Same level thing.  It could do anything up to and including permanent damage.

HLT: This instruction has always meant "Wait for the next interrupt", it's one that we added (it's not in the Notch specs).

**Comment by bshepherdson** [comment] 2016-11-29 14:21
## On the Above

- Meisaka is correct about `SP` starting at 0. The stack is "full-descending" or "decrement-before", to borrow ARM terminology, meaning that when pushing a value the `SP` is decremented first (to `0xffff`, say) and then a value stored there.
- "Undefined" for adding and removing hardware sounds good to me. It also underlines that even if you try to figure out how it works and support it, the behavior could change later.
- If there's going to be a debug device (see #30) then illegal instructions should be one of the things that triggers the debugger, I think. Having them be a no-op otherwise is fine with me.

## New questions

### Cycle Timing
How many cycles to run `ADD [A+4], 0xff00`?

- `0xff00` is a long literal, so that's 1 cycle.
- Reading `[A+4]` takes 1 extra cycle.
- `ADD` takes 2 cycles.
- And the tricky bit: writing back to `[A+4]` takes another 1 cycle?

If I'm right that reading and writing to `[A+4]` each cost a cycle, the total is 5. If it's only charged once, 4. It would be good to have it confirmed in the spec either way, perhaps with such an example.

### Cycle Timing, round 2

Does entering the interrupt handler cost cycles? It does push two values to the stack, after all. This is badly documented in many real processors too, so I guess the DCPU is no exception, but it would be a good idea to document that eg. three cycles are burned before the user's handler at `IA` runs.

### Signed Division

Division is a pain in the ass. In particular, when dividing and modding negative values, there are two possible schemes, known as "symmetric division" (rounding towards 0) and "floored division" (rounding toward negative infinity).

Consider the division identity: if `b / a = q` with remainder `r`, we must have `b = a*q + r`. But there are two possible ways to achieve that:
    - Symmetric: `-7 / 3 = -2 R -1` (`-7 = 3*(-2) - 1`) Note that the true answer of `-2.5` is rounded toward 0 to give `-2`.
    - Floored: `-7 / 3 = -3 R 2` (`-7 = 3*(-3) + 2`) True answer `-2.5` rounded toward negative infinity.
 
Examples in the spec are the best way to make sure everyone is on the same page. I can supply a pull request if you like; I know way more about this than I'd like, from implementing Forth systems.

Symmetric division is generally less surprising, in my opinion, and I recommend it.

### Halt vs. Interrupt Queue

If I `HLT` with interrupt queueing enabled, what happens? I can see four(!) paths:

1. Locked up forever, oops.
2. Halts until a new interrupt comes in and is added to the queue.
3. Resumes immediately if the queue is nonempty, or waits until one is added if it's empty.
4. Queueing becomes disabled when `HLT` executes, which naturally means the halt ends immediately if there were interrupts in the queue.

I encourage either 3 or 4, and we should document it clearly in whichever case.

### Device numbering

If `HWN` returns 7, are the 7 devices numbered 0-6 or 1-7?

### Order of operations

Suppose `EX=5` and I do `ADD EX,7`. `ADD` sets `EX` to 1 on an overflow and 0 otherwise, but when? There's no overflow here, so does `EX=0`, `7` or `12` after the instruction?

I suggest the internal order should be:

1. Read the right-hand operand (`7`)
2. Read the left-hand operand (`EX=5`)
3. Set `EX` per `ADD`'s spec (`EX=0`)
4. Write the output (`EX=7+5=12`)

But there are other possibilities that match the spec as written now.

**Comment by andyleap** [comment] 2016-11-29 14:39
Cycle Timing
------
Currently it'd be 5, though the "cost" seems to be reading the extra literal, so I wouldn't be adverse to making it 4.

Cycle Timing, round 2
-------
Entering interrupt handler is currently free

Signed Division
-------
DIV is unsigned, of course.  DVI should be symmetric, as we make both operands positive, do the division, then apply the proper sign.

Halt vs. Interrupt Queue
------
Currently, you'd halt the DCPU permanently, though I'd lean towards 4

Device numbering
------
Devices start at 0, so 0-6.

Order of operations
-----
EX would be 0.  All EX sets occur after the output is written, all reads occur before anything else is done.  Current internal order is:

1. Read a (right hand)
2. Read b (left hand)
3. Set output
4. Set EX

**Comment by paultech** [comment] 2017-02-11 14:11
Some of this info can be put into the wiki so I can close the issue.

**Closed as completed** 2017-04-03 17:59 UTC
